version: "3.8"

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=mats.funke@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_letsencrypt:/letsencrypt
    networks:
      - web
    restart: unless-stopped

  personal-website:
    build: .
    container_name: personal-website
    labels:
      - "traefik.enable=true"

      # Main website route
      - "traefik.http.routers.personal-website.rule=Host(`matsjfunke.com`)"
      - "traefik.http.routers.personal-website.entrypoints=websecure"
      - "traefik.http.routers.personal-website.tls.certresolver=myresolver"
      - "traefik.http.services.personal-website.loadbalancer.server.port=3000"

        # MCP server route - dedicated subdomain with path transformation
      - "traefik.http.routers.mcp.rule=Host(`mcp.matsjfunke.com`) && PathPrefix(`/mcp`)"
      - "traefik.http.routers.mcp.entrypoints=websecure"
      - "traefik.http.routers.mcp.tls.certresolver=myresolver"
      - "traefik.http.services.mcp.loadbalancer.server.port=3000"

      # Transform /mcp to /api/mcp for Next.js routing
      - "traefik.http.middlewares.mcp-stripprefix.stripprefix.prefixes=/mcp"
      - "traefik.http.middlewares.mcp-addprefix.addprefix.prefix=/api/mcp"

      # Add CORS headers for MCP API
      - "traefik.http.middlewares.mcp-cors.headers.accessControlAllowMethods=GET,POST,OPTIONS,DELETE"
      - "traefik.http.middlewares.mcp-cors.headers.accessControlAllowHeaders=Content-Type,Authorization,mcp-session-id"
      - "traefik.http.middlewares.mcp-cors.headers.accessControlAllowOrigin=*"

      # Chain middlewares: strip /mcp, add /api/mcp, then CORS
      - "traefik.http.routers.mcp.middlewares=mcp-stripprefix,mcp-addprefix,mcp-cors"

    networks:
      - web
    restart: unless-stopped
    depends_on:
      - traefik

volumes:
  traefik_letsencrypt:

networks:
  web:
    external: false
